import SlideForm from "./components/SlideForm";
import Eraser from "./components/Tools/Eraser";
import EyeDropper from "./components/Tools/EyeDropper";
import Swatch from "./components/swatch";
import Pencil from "./components/Tools/Pencil";
import { Color } from "./components/swatch";
import ToolBar from "./components/Tools/ToolBar";
new Swatch(Color.red);
new Swatch(Color.white);
new Swatch(Color.black);
new Swatch(Color.blue);
new Swatch(Color.green);
new Swatch(Color.orange);
new Swatch(Color.pink);
new SlideForm();
new ToolBar();
